python/ecep/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static

from django.views.generic import TemplateView, RedirectView
from sitemap import LocationSiteMap, StaticViewSitemap
from django.contrib.gis import admin
admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('portal',),
}

from portal.views import *

sitemaps = {'location': LocationSiteMap, 'static': StaticViewSitemap}

urlpatterns = patterns(
    '',
    # Index page is in the 'portal' app
    #url(r'^$', Index.as_view(), name='index'),
    #url(r'^about$', About.as_view(), name='about'),
    #url(r'^updates$', Updates.as_view(), name='updates'),
    #url(r'^city-resources$', CityResources.as_view(), name='city-resources'),
    #url(r'^how-to-apply$', HowToApply.as_view(), name='how-to-apply'),
    #url(r'^connect$', Connect.as_view(), name='connect'),
    #url(r'^announcements$', Announcements.as_view(), name='announcements'),
    #url(r'^outreach$', OutreachRedesign.as_view(), name='outreach'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type="text/plain")),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/favicons/favicon.ico')),

    # Redesign testing ground
    #url(r'^family-resource-centers',  FamilyResourceCenters.as_view(), name='family-resource-centers'),
    #url(r'^faq$', FAQ.as_view(), name='faq'),
    #url(r'^families$', Programs.as_view(), name='families'),
    #url(r'^programs$', Programs.as_view(), name='programs'),
    #url(r'^resources$', Resources.as_view(), name='resources'),

    # Search
    url(r'search/', Search.as_view(), name="search"),

    # Blog
    #url(r'^blog/$', Blog.as_view(), name="blog"),
    #url(r'^blog/hughes-library$', Blog.as_view(), name="blog-hughes"),

    # portal autocomplete api
    url(r'^api/autocomplete/$', 'portal.views.portal_autocomplete'),

    # Enroll
    #url(r'enroll/?$', HowToApply.as_view(), name='enroll-faq'),

    # Location Views
    # Need to pass id to view for sitemap, but don't need to do anything with it since this is handled with javascript
    url(r'^location/(\d+)/$', 'portal.views.location', name='location-view'),
    url(r'^location/(?P<location_id>\d+)/$', 'portal.views.location', name='location-view'),
    url(r'^location/(?P<location_id>\d+)/(?P<slug>[\w-]+)/$', 'portal.views.location', name='location-view'),
    url(r'^map/(\d+)/$', 'portal.views.location_map', name='location-map-view'),

    # Starred Location Views
    url(
        r'^starred/?[0-9,]*/$',
        Starred.as_view(),
        name='starred',
    ),
    url(
        r'^favorites/?[0-9,]*/$',
        Starred.as_view(),
        name='favorites',
    ),

    # i18n
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', kwargs=js_info_dict, name='javascript-catalog'),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^i18n/(?P<language>.+)/$', 'portal.views.setlang', name='setlang'),

    # Admin interface
    url(r'^admin/', include(admin.site.urls)),

    # Sitemaps
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

urlpatterns += i18n_patterns(
    '',

    # Location API
    url(r'^api/location/(?P<location_ids>[0-9,]*)/$', 'portal.views.location_api'),
    url(r'^api/location/$', 'portal.views.location_api'),
    url(r'^api/location/json/$', 'portal.views.location_json_api'),
    url(r'^api/starred-location/(?P<location_ids>[0-9,]*)/$', 'portal.views.starred_location_api'),
    url(r'^api/map/json/$', 'portal.views.api_map_json'),

    # Neighborhood API
    url(r'^api/neighborhood/$', 'portal.views.neighborhood_api'),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

python/ecep/portal/models.py
from django.contrib.gis.db import models
from portal.templatetags.portal_extras import nicephone
from django.template.defaultfilters import title
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Model fields need to be translated lazily
from django.utils.translation import ugettext as _, ugettext_lazy


class Neighborhood(models.Model):
    """Model for Neighborhoods
    Model for a Neighborhood, which is simply a geographic area with a name
    boundary -- MultiPolygon for the neighborhood
    primary_name -- Display name for the neighborhood
    secondary_name -- Detailed/Unformatted name for the neighborhood
    """
    boundary = models.MultiPolygonField()
    primary_name = models.CharField(max_length=100)
    secondary_name = models.CharField(max_length=100)
    # GeoManager is required so Django knows it can do geospatial queries to the db
    objects = models.GeoManager()

    def save(self, *args, **kwargs):
        """ Override for Model.save()
        Updates neighborhood relation for all Locations that intersect the new Neighborhood boundaries
        """
        super(Neighborhood, self).save(*args, **kwargs)

        # update location AFTER updating neighborhood polygon
        locations = Location.objects.filter(geom__intersects=self.boundary)
        for location in locations:
            # update if no neighborhood or the neighborhood is different
            if location.neighborhood is None or location.neighborhood.id != self.id:
                location.save()

    def get_center(self):
        """Returns a dictionary representation of the neighborhood's centroid.

        Used to add functionality to zoom on neighborhood when explore button clicked.
        """
        center = self.boundary.centroid.coords
        return {'lng': center[0], 'lat': center[1]}

    def __unicode__(self):
        return unicode(self.primary_name)


class Location(models.Model):
    """Model for school locations in Chicago
    """
    EMPTY = ''
    NONE = 'None'
    LICENSED = 'Licensed'
    BRONZE = 'Bronze'
    SILVER = 'Silver'
    GOLD = 'Gold'

    Q_RATING_CHOICES = (
        (EMPTY, ugettext_lazy('Select a rating')),
        (NONE, ugettext_lazy('None')),
        (LICENSED, ugettext_lazy('Licensed')),
        (BRONZE, ugettext_lazy('Bronze')),
        (SILVER, ugettext_lazy('Silver')),
        (GOLD, ugettext_lazy('Gold')),
    )

    LOCATION_TYPE_CHOICES = (
        (0, 'Normal Location'),
        (1, 'Application Site'),
    )

    HIGH = 'Slots Available'
    MEDIUM = 'Few or No Slots'

    AVAILABILITY_CHOICES = (
        (HIGH, ugettext_lazy('Slots Available')),
        (MEDIUM, ugettext_lazy('Limited Availability')),
    )

    active = models.BooleanField('Active', default=0, blank=True)
    display = models.BooleanField('Display', default=0, blank=True)
    copa_key = models.IntegerField('COPA Key', default=0, blank=True)
    ecm_key = models.IntegerField('ECM Key', default=0, blank=True)
    site_name = models.CharField('Site Name', max_length=100)
    site_type = models.IntegerField('Site Type', default=0, choices=LOCATION_TYPE_CHOICES)
    address = models.CharField('Address', max_length=75)
    city = models.CharField('City', max_length=75)
    state = models.CharField('State', max_length=2)
    zip = models.CharField('Zip Code', max_length=10)
    neighborhood = models.ForeignKey('Neighborhood', null=True)
    phone = models.CharField(ugettext_lazy('Phone Number'), max_length=20, blank=True)
    q_rating = models.CharField(ugettext_lazy('Quality Rating'), choices=Q_RATING_CHOICES, max_length=10, blank=True)
    url = models.CharField(ugettext_lazy('Website'), max_length=256, blank=True)
    q_stmt = models.TextField(ugettext_lazy('Description'), blank=True)
    enrollment = models.TextField(ugettext_lazy('Enrollment Process'), blank=True)
    accred = models.CharField(ugettext_lazy('Accreditation'), max_length=100, blank=True)
    prg_hours = models.CharField(ugettext_lazy('Program Hours'), max_length=200, blank=True)
    is_age_lt_3 = models.NullBooleanField(ugettext_lazy('Ages 0 - 3'))
    is_age_gt_3 = models.NullBooleanField(ugettext_lazy('Ages 3 - 5'))
    is_full_day = models.NullBooleanField(ugettext_lazy('Full Day'))
    is_part_day = models.NullBooleanField(ugettext_lazy('Half Day'))
    is_school_year = models.NullBooleanField(ugettext_lazy('School Year'))
    is_full_year = models.NullBooleanField(ugettext_lazy('Year-round'))
    ages = models.CharField(ugettext_lazy('Ages Served'), max_length=50, blank=True)
    is_full_week = models.NullBooleanField(ugettext_lazy('Full Week'))
    is_part_week = models.NullBooleanField(ugettext_lazy('Part Week'))
    language_1 = models.CharField('Language 1 (other than English)', max_length=200, blank=True)
    language_2 = models.CharField('Language 2 (other than English)', max_length=200, blank=True)
    language_3 = models.CharField('Language 3 (other than English)', max_length=200, blank=True)
    is_community_based = models.NullBooleanField(ugettext_lazy('Community Based'))
    is_cps_based = models.NullBooleanField(ugettext_lazy('CPS Based'))
    is_home_visiting = models.NullBooleanField(ugettext_lazy('Offers Home Visiting'))
    accept_ccap = models.NullBooleanField(ugettext_lazy('Accepts CCAP'))
    is_hs = models.NullBooleanField(ugettext_lazy('Head Start'))
    is_ehs = models.NullBooleanField(ugettext_lazy('Early Head Start'))
    open_house = models.TextField(ugettext_lazy('Open House'), blank=True)
    curriculum = models.TextField(ugettext_lazy('Curriculum'), blank=True)
    email = models.EmailField(blank=True)

    # Keeps track of whether or not new locations have been approved by the admin
    accepted = models.BooleanField(ugettext_lazy('Approved'), default=False)

    # COPA alottment status, classroom availability
    availability = models.CharField(ugettext_lazy('Availability'), choices=AVAILABILITY_CHOICES, max_length=25, blank=True)

    # Misc future fields, mirroring COPA system columns:
    universal_application = models.BooleanField('COPA Univeral Application', default=False, blank=True)
    preschool_application = models.BooleanField('COPA Preschool Application', default=False, blank=True)
    copa_neighborhood = models.CharField('Neighborhood Name (COPA)', max_length=50, blank=True)
    copa_neighborhood_id = models.IntegerField('Neighborhood Name ID', default=0, blank=True)
    site_name_alternate = models.CharField('Alternate Site Name', max_length=100, blank=True)
    last_modified_on = models.CharField('Last Modified On', max_length=50, blank=True)

    # To get these placeholder fields to show up in the UI, replace
    # 'Placeholder 1' and 'Placeholder 2' in the lines below with
    # real labels, and add 'placeholder_1' and 'placeholder_2' to the
    # 'display_include' list. Also, in admin.py, browse to the
    # LocationAdmin class and add the appropriate entries to the
    # fieldsets list.
    placeholder_1 = models.TextField('Placeholder 1', blank=True)
    placeholder_2 = models.TextField('Placeholder 2', blank=True)

    geom = models.PointField('Geometry', srid=4326, null=True)
    objects = models.GeoManager()

    # List of simple/boolean fields that should be displayed by Location renderers/views
    display_include = {
        'ages', 'accred', 'accept_ccap', 'is_home_visiting', 'is_hs', 'is_ehs',
        'is_community_based', 'is_cps_based', 'open_house', 'curriculum',
    }

    # List of fields that should be hidden when left blank
    hide_if_none = {
        'open_house', 'curriculum',
    }

    display_order = dict((k, v) for v, k in enumerate([
            'open_house',
            'accred', 'ages', 'description', 'enrollment', 'duration_hours',
            'weekday_availability', 'languages', 'program_info',
            'curriculum', 'quality_rating'
        ]))

    q_rating_translations = [
        ugettext_lazy('None'),
        ugettext_lazy('Licensed'),
        ugettext_lazy('Bronze'),
        ugettext_lazy('Silver'),
        ugettext_lazy('Gold')
    ]

    def __unicode__(self):
        return unicode(self.site_name)

    def verbose_name(self, field):
        """
        Given the name of field, returns the verbose_name property for it
        """
        return unicode(self._meta.get_field_by_name(field)[0].verbose_name)

    @property
    def is_enrollment(self):
        if self.site_type == 1:
            return True
        else:
            return False

    def combine_languages(self):
        lang_list = [lang for lang in self.language_1, self.language_2, self.language_3 if lang]
        languages = ", ".join(lang_list)
        return languages

    def combine_other_features(self):
        other_features = ''
        return other_features

    @staticmethod
    def get_filter_fields():
        """
        Returns all boolean fields that should be used for filtering Location objects

        This method does not use a static list of names, but rather inspects
        the meta class attached to the model to introspect on the field types.
        This also has the benefit of providing the verbose name of the field.
        """

        # TODO: This relies on fields being ordered in the fields object in the
        # same order they're defined above.  This is probably a sketchy assumption.
        exclude = ['is_montessori', 'is_special_ed']

        fields = []
        for field in Location._meta.fields:
            if (field.get_internal_type() == 'NullBooleanField' and
                    not field.get_attname() in exclude):
                fields.append((field.get_attname(), _(field.verbose_name),))

        return fields

    def get_boolean_fieldnames(self):
        """
        Extracts list of boolean field names from model
        """
        fields = self._meta.fields
        return [field.name for field in fields if field.get_internal_type() == 'NullBooleanField']

    def is_true_bool_field(self, field):
        """

python/ecep/portal/templates/iframe/location-map.html
{% extends "iframe/base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load portal_extras %}
{% load svg %}

{% block title %}{{ loc.item.site_name }} - {{ loc_neighborhood }} - {% trans "Chicago Early Learning" %}{% endblock %}

{% block otherhead %}
{% endblock %}

{% block base %}
<div id="location-container" class="container container-bottom-4">
  <div class="location-top-headers">
    <div class="location-name">
      <h1 class="black">{{ location.site_name }}</h1>
    </div>
    <div class="location-address">
      <h2 class="gray">{{ location.address }}</h2>
    </div>
    <div><p class="gray"><i>{% trans 'Use two fingers to navigate the map.' %}</i></p></div>
  </div>
  <div class="location-map">
    <div id="location-map" 
      data-lat="{{ loc.position.lat|stringformat:"f" }}"
      data-lng="{{ loc.position.lng|stringformat:"f" }}" 
      {% if request.GET.lat and request.GET.lng %}
      data-address-latitude="{{ request.GET.lat }}"
      data-address-longitude="{{ request.GET.lng }}"
      {% endif %}
      class="single-location-map"></div>
  </div>
  <div class="row py-3">
    <div class="col-sm-12">
      <div class="location-action-button">
        <a href="{% url 'location-view' location_id=location.id %}" class="btn btn-orange btn-block">{% trans 'More Info' %}</a>
      </div>
    </div>
    <div class="col-sm-12">
      <div class="location-action-button">
        <a href="https://maps.google.com/maps?saddr=current+location&daddr={{location.address}}+{{location.city}}+{{location.state}}+{{location.zip}}" class="btn btn-gray btn-block">{% trans 'Get Directions' %}</a>
      </div>
    </div>
    {% if location.universal_application %}
    <div class="col-sm-12">
      <div class="location-action-button">
        <a href="{{ location.get_copa_url }}?site1={{ location.copa_key }}" class="btn btn-blue btn-block">{% trans 'Apply Today!' %}</a>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
require(['location-marker'], function() { });
</script>
{% endblock %}

python/ecep/portal/templates/iframe/location.html
{% extends "iframe/base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load portal_extras %}
{% load svg %}

{% block title %}{{ loc.item.site_name }} - {{ loc_neighborhood }} - {% trans "Chicago Early Learning" %}{% endblock %}

{% block otherhead %}
{% endblock %}

{% block base %}
<div id="location-container" class="container container-top-2 container-bottom-4">
  <div class="location-map hidden-md-down">
    <div id="location-map" data-lat="{{ loc.position.lat|stringformat:'f' }}" data-lng="{{ loc.position.lng|stringformat:'f' }}" class="single-location-map"></div>
    <div class="location-divider"></div>
  </div>
  <div class="location-block">
    <div class="location-top row">
      <div class="location-top-headers col-md-8">
        <div class="location-name">
          <h1 class="black">{{ location.site_name }}</h1>
        </div>
        <div class="location-address">
          <h2 class="dark-gray">{{ location.address }}</h2>
        </div>
        {% if location.phone %}
        <div class="location-phone">
          <a class="a-orange" href="tel:{{location.phone}}">{{ location.phone }}</a>
        </div>
        {% endif %}
        {% if location.url %}
        <div class="location-url">
          <a class="a-orange" href="{{location.url}}">{% trans "View Website" %} &#x2197;</a>
        </div>
        {% endif %}
      </div>
      <div class="location-top-actions col-md-4">
        <div class="location-action-button hidden-md-down">
          <a href="https://maps.google.com/maps?saddr=current+location&daddr={{location.address}}+{{location.city}}+{{location.state}}+{{location.zip}}" class="btn btn-lg btn-gray btn-block">{% trans 'Get Directions' %}</a>
        </div>
        <div class="location-action-button hidden-lg-up">
          <a class="btn btn-lg btn-gray btn-block" href="{% url 'location-map-view' location.id %}">{% trans 'View On Map' %}</a>
        </div>
        <div class="location-action-button">
          <a data-redirect="/favorites/" data-location="{{ location.id }}" class="btn btn-lg btn-gray btn-block compare-btn">{% trans 'Compare Location' %}</a>
        </div>
        {% if location.universal_application %}
        <div class="location-action-button">
          <a href="{{ location.get_copa_url }}?site1={{ location.copa_key }}" class="btn btn-lg btn-orange btn-block">{% trans 'Apply Today!' %}</a>
        </div>
        {% endif %}
      </div>
    </div>
  </div>

  {% if location.q_stmt %}
  <!-- Location description -->
  <div class="location-block">
    <div class="location-description py-5">
      <div class="row">
        <div class="location-description-header col-md-12">
          <h2 class="blue">{% trans 'Description' %}</h2>
        </div>
        <div class="location-description-content col-md-12">
          {{ location.q_stmt|safe }}
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <!-- Ages Served -->
  <div class="location-block">
    <div class="location-ages py-5">
      <div class="row">
        <div class="location-ages-header col-md-12">
          <h2 class="blue">{% trans 'Ages Served' %}</h2>
        </div>
        <div class="location-ages-content col-md-12">
          <div class="location-inline">
            <div class="location-infants">
              <div class="location-svg">
                {% if location.is_age_lt_3 %} 
                  <div class="svg-inline-link svg-green">{% svg 'icons/checkmark' %}</div>
                {% else%}
                  <div class="svg-inline-link svg-red">{% svg 'icons/cross' %}</div>
                {% endif %}
              </div>
              <div class="location-message">
                <span>{% trans 'Ages 0 to 3' %}</span>
              </div>
            </div>
            <div class="location-preschool">
              <div class="location-svg">
                {% if location.is_age_gt_3 %} 
                  <div class="svg-inline-link svg-green">{% svg 'icons/checkmark' %}</div>
                {% else%}
                  <div class="svg-inline-link svg-red">{% svg 'icons/cross' %}</div>
                {% endif %}
              </div>
              <div class="location-message">
                <span>{% trans 'Ages 3 to 5' %}</span>
              </div>
            </div>
            <div class="location-ages-disclaimer">
            {% if location.is_age_lt_3 %}
              <p><em>{% blocktrans %}<b>Ages 0 - 3:</b> If your child will be younger than 3 years old prior to September 1, 2017, there are infant/toddler programs available. Please contact the site directly for enrollment information for these programs.{% endblocktrans %}</em></p>
            {% endif %}

            {% if location.is_age_gt_3 and not location.universal_application %}
              <p><em>{% blocktrans %}<b>Ages 3 - 5:</b> If your child is 3 or 4 years old prior to September 1, 2017, your child will be eligible for preschool programs.{% endblocktrans %}</em></p>
            {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if location.availability %}
  <!-- Availability -->
  <div class="location-block">
    <div class="location-availability py-5">
      <div class="row">
        <div class="location-availability-header col-md-12">
          <h2 class="blue">{% trans 'Seats Available' %}</h2>
        </div>
        <div class="location-availability-content col-md-12">
          <div class="location-inline">
            <div class="location-availability-block">
              <div class="location-svg">
                {% if location.availability == 'Slots Available' %} 
                  <div class="svg-inline-link svg-green">{% svg 'icons/checkmark' %}</div>
                {% elif location.availability == 'Few or No Slots' %} 
                  <div class="svg-inline-link svg-yellow">{% svg 'icons/checkmark' %}</div>
                {% endif %}
              </div>
              <div class="location-message">
                <span>{{ location.get_availability_display }}</span>
              </div>
            </div>
            <div class="location-availability-disclaimer">
              <p><em>{% blocktrans %}Note: Availability and placement are subject to eligibility{% endblocktrans %}</em></p>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}

  <!-- Duration and Program Info --> 
  <div class="location-block">
    <div class="location-group-info">
      <div class="location-dividers row">
        <div class="location-divider-block col-md-6 my-5">
          <div class="location-group-header">
            <h2 class="blue">{% trans 'Duration and Hours' %}</h2>
          </div>
          <div class="location-content">

            {% if location.is_full_day and location.is_part_day %}
              <p>{% trans 'Full Day' %}, {% trans 'Half Day'%}</p>
            {% elif location.is_full_day %}
              <p>{% trans 'Full Day'%}</p>
            {% elif location.is_part_day %}
              <p>{% trans 'Half Day' %}</p>
            {% endif %}

            {% if location.is_full_year and location.is_school_year %}
              <p>{% trans 'Year-round' %}, {% trans 'School Year' %}</p>
            {% elif location.is_full_year %}
              <p>{% trans 'Year-round' %}</p>
            {% elif location.is_school_year %}
              <p>{% trans 'School Year' %}</p>
            {% endif %}

            {% if location.prg_hours %}<p>{{ location.prg_hours }}</p>{% else %}<p><em>{% trans 'No Hours Listed' %}</em></p>{% endif %}
          </div>
        </div>
        <div class="location-divider-block col-md-6 my-5">
          <div class="location-group-header">
            <h2 class="blue">{% trans 'Program Information' %}</h2>
          </div>
          <div class="location-content">
          {% if location.is_cps_based %}<p>{% trans 'CPS Based' %}</p>{% endif %}
          {% if location.is_community_based %}<p>{% trans 'Community Based' %}</p>{% endif %}
          {% if location.is_hs %}<p>{% trans 'Head Start' %}</p>{% endif %}
          {% if location.is_ehs %}<p>{% trans 'Early Head Start' %}</p>{% endif %}
          {% if location.is_home_visiting %}
          <p>{% trans 'Offers Home Visiting' %}</p>
          <p><em>{% trans 'If you are interested in enrolling your child in this home visiting program please contact this site directly.' %}</em></p>
          {% endif %}
        </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Languages, Other Features -->
  {% if location.language_1 or fields.other_features %}
  <div class="location-block">
    <div class="location-group-info">
      <div class="location-dividers row">
        {% if location.language_1 %}
        <div class="location-divider-block col-md-6 my-5">
          <div class="location-group-header">
            <h2 class="blue">{% trans 'Languages' %}</h2>
          </div>
          <div class="location-content">
            <p>{{ location.language_1 }}</p>
          </div>
        </div>
        {% endif %}
        {% if loc.other_features %}
        <div class="location-divider-block col-md-6 my-5">
          <div class="location-group-header">
            <h2 class="blue">{% trans 'Other Features' %}</h2>
          </div>
          <div class="location-content">
            <p>{{ fields.other_features|join:", " }}</p>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% endif %}

  <!-- Accreditation, Quality Rating --> 
  <div class="location-block">
    <div class="location-special">
      <div class="location-dividers row">
        {% if location.accred %}
        <div class="location-divider-block col-md-6 my-5">
          <div class="location-block-header">
            <h2 class="blue">{% trans 'Accreditation' %}</h2>
          </div>
          <div class="location-block-content">
            <h3 class="orange py-2">{{ location.accred }}</h3>
          </div>
          <div class="location-inline">
            <div class="location-svg">
              <div class="svg-inline-link svg-star">{% svg 'illustrations/star' %}</div>
            </div>
            <div class="location-message">
              <h3 class="blue"><span>{% trans 'What does "Accreditation" mean?' %}</span></h3>
            </div>
          </div>
          <div class="location-special-description">
            <p>{% blocktrans %}Programs that receive national accreditation have demonstrated quality in areas such as teaching, curriculum, learning assessments, health, community relationships, physical environment, and management.{% endblocktrans %}</p>
          </div>
        </div>
        {% endif %}
        <div class="location-divider-block col-md-6 my-5">
          <div class="location-block-header">
            <h2 class="blue">{% trans 'Quality Rating' %}</h2>
          </div>
          <div class="location-block-content">
            <h3 class="orange py-2">{{ location.get_q_rating_display }}</h3>
          </div>
          <div class="location-inline">
            <div class="location-svg">
              <div class="svg-inline-link svg-ribbon">{% svg 'illustrations/ribbon' %}</div>
            </div>
            <div class="location-message">
              <h3 class="blue"><span>{% trans 'What does "Quality Rating" mean?' %}</span></h3>
            </div>
          </div>
          <div class="location-special-description">
            <p>{% blocktrans %}Quality Rating indicates the quality of a site based on the Excelerate Illinois system. More information can be found at <a class="a-orange" href="http://excelerateillinois.com">ExcelerateIllinois.com</a>.{% endblocktrans %}</p>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- End block -->
  <div class="location-provider-message py-5">
    <p>{% blocktrans %}Are you a provider who works at this early learning center and needs to make changes to information on this page? <a class="a-orange" href="https://smartchicago2012.wufoo.com/forms/chicago-early-learning-provider-form/">Click here!</a><b>{% endblocktrans %}</b></p>
  </div>

</div>
{% endblock %}

{% block scripts %}
<script>
require(['location-marker'], function() { });
</script>
{% endblock %}